MesdJasperReportBundle_render_cached_asset:
    path:    /assets/{asset}/{requestId}
    defaults:   { _controller: MesdJasperReportBundle:Report:displayCachedAsset }

MesdJasperReportBundle_export_cached_report:
    path:    /export/{requestId}/{format}
    defaults:   { _controller: MesdJasperReportBundle:Report:exportCachedReport }

MesdJasperReportBundle_ajax_options:
    path:    /ajaxoptions/{inputId}
    defaults:   { _controller: MesdJasperReportBundle:Report:ajaxOptions }
