mesd_jasperreport_render_cached_asset:
    pattern:    /assets/{asset}/{requestId}
    defaults:   { _controller: MESDJasperReportBundle:Report:displayCachedAsset }

mesd_jasperreport_export_cached_report:
    pattern:    /export/{requestId}/{format}
    defaults:   { _controller: MESDJasperReportBundle:Report:exportCachedReport }