parameters:

services:
    mesd.jasperreport.client:
        class: MESD\Jasper\ReportBundle\Services\ClientService
        arguments: [ @service_container ]

    mesd.jasperreport.loader:
        class: MESD\Jasper\ReportBundle\Services\LoaderService
        arguments: [ @router ]

    mesd.jasperreport.history:
        class: MESD\Jasper\ReportBundle\Services\HistoryService
        arguments: [ @doctrine, @security.context ]

    mesd.jasperreport.security:
        class: MESD\Jasper\ReportBundle\Services\SecurityService
        arguments: [ @security.context ]

    mesd.jasperreport.display_helper:
        class: MESD\Jasper\ReportBundle\Helper\DisplayHelper
        arguments: [ @service_container ]

    mesd.jasperreport.twig.extension.report:
        class: MESD\Jasper\ReportBundle\Twig\Extension\ReportExtension
        arguments: [ @mesd.jasperreport.display_helper ]
        tags:
            - { name: twig.extension }